export const beerStyles = [
  "Barrel Aged Biere de Garde",
  "Brettanomyces Saison",
  "Barrel-Aged Saison",
  "Barrel-Aged Saison",
  "Mixed-Fermentation Saison",
  "Tart Saison",
  "Pilsner",
  "Session India Pale Ale",
  "Sour Ale with Lactose",
  "India Pale Ale",
  "India Pale Ale",
  "India Pale Ale",
  "Galaxy India Pale Ale",
  "India Pale Ale",
  "India Pale Ale",
  "India Pale Ale",
  "Double Dry-Hopped Double India Pale Ale",
  "Double India Pale Ale",
  "Double India Pale Ale w/ Yumberry",
  "Coffee Oatmeal Milk Stout",
  "Imperial Stout",
  "House India Pale Ale",
  "Brettanomyces Saison",
  "Keller-Style Pilsner",
  "Dry Hopped Brettanomyces Saison",
  "Oak Aged Saison with Mandarin",
  "Oak-Aged Breakfast Sour",
  "Dry Hopped Brettanomyces Saison",
  "Farmhouse Pale Ale",
  "Hoppy Saison",
  "Hoppy Saison",
  "Dry-Hopped Table Saison",
  "All Colorado Saison",
  "Dry-Hopped Grisette",
  "Brett Saison",
  "Farmhouse Pale Ale",
  "Table Saison",
  "Mandarin Saison",
  "Hoppy Saison",
  "Belgian Pale Ale",
  "Smoothie-Style Sour",
  "Smoothie-Style Sour",
  "American Wild Ale",
  "Smoothie-Style Sour",
  "Smoothie-Style Sour",
  "Smoothie-Style Sour",
  "Smoothie-Style Sour",
  "Smoothie-Style Sour",
  "Dry-Hopped Gose",
  "Blackberry Cobbler Sour",
  "Gose-Style Ale",
  "Pale Ale with Rooibos",
  "Session India Pale Ale",
  "New Zealand Pale Ale",
  "English Brown Ale",
  "American Pale Ale",
  "IPA w/ Passion Fruit",
  "India Pale Ale",
  "DDH Double India Pale Ale",
  "India Pale Ale",
  "Double India Pale Ale",
  "India Pale Ale",
  "Double India Pale Ale",
  "American Pale Ale",
  "India Pale Ale with Lactose",
  "India Pale Ale with Tangerine",
  "India Pale Ale",
  "Blueberry India Pale Ale",
  "India Pale Ale",
  "Double India Pale Ale",
  "India Pale Ale",
  "DDH India Pale Ale",
  "India Pale Ale",
  "India Pale Ale",
  "Extra Pale Ale",
  "India Pale Ale",
  "Double India Pale Ale",
  "Double India Pale Ale",
  "India Pale Ale",
  "Double India Pale Ale",
  "Barrel-Aged Imperial Chocolate Stout",
  "Barrel–Aged Imperial Pastry Stout",
  "Imperial Chocolate Stout",
  "Barrel-Aged Imperial Coffee Stout",
  "Oatmeal Milk Stout",
  "Imperial Coffee Stout",
  "Robust American Porter",
  "Robust American Porter",
  "Imperial Breakfast Porter",
  "Imperial Pastry Stout",
  "Imperial Chocolate Stout",
  "Imperial Oatmeal Milk Stout",
  "Bourbon Barrel Aged Imperial Stout",
  "Bourbon Barrel Aged Imperial Stout",
  "Imperial Coffee Stout",
  "Imperial Breakfast Porter",
  "Maple Syrup Bourbon Barrel Aged Breakfast Porter",
  "Bourbon Barrel Aged Breakfast Porter"
];
